/**
 * site-data.js — Pre-seeded family data for ALL devices
 * Generated by Admin → "Publish to Site"
 * Upload this file to GitHub whenever you make changes in Admin
 * so all visitors (mobile, desktop, any browser) see the same data.
 */
(function(){
  var DATA = {};  // Will be populated when Admin publishes

  // Only pre-seed if the key doesn't exist locally
  // (local edits in admin take priority)
  var KEYS = [
    'nukala_tree_data','nukala_gallery','nukala_history','nukala_facts',
    'nukala_events','nukala_recipes','nukala_achievements','nukala_videos',
    'nukala_polls','nukala_contacts','nukala_settings','nukala_page_vis',
    'nukala_sitewide','nukala_home','nukala_heropage','nukala_newpages',
    'nukala_contactpage2','nukala_gallerypage2','nukala_typography',
    'nukala_navmenu','nukala_loginpage'
  ];

  KEYS.forEach(function(k){
    if(DATA[k] !== undefined && !localStorage.getItem(k)){
      localStorage.setItem(k, JSON.stringify(DATA[k]));
    }
  });
})();
